apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
   name: workshp-oper-role
   namespace: workshp
   labels:
      name: workshp-oper-role

rules:
- apiGroups: [ "" ] # core
  resources: [ "pods", "pods/log", "services" ]
  verbs:
  - get
  - list
  - watch
- apiGroups: [ "apps" ] # core
  resources: [ "deployments" ]
  verbs:
  - get
  - list
  - watch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
   name: workshp-oper-rolebinding
   namespace: workshp
   labels:
      name: workshp-oper-binding

roleRef:
   apiGroup: rbac.authorization.k8s.io
   kind: Role
   name: workshp-oper-role

subjects:
- kind: User 
  name: fred 
  namespace: workshp
