apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: fortune-secret
  namespace: workshp
spec:
  encryptedData:
    apiKey: AgA4/4WQGUEf2wv+uMWRT6qBtmbd03XVdq0312eKJ+06uKXkui+sax8ecqBV+YZ642t/Bc5dZdISt8AlPzP/+hwTmQJkQiOAvfzhGKPbLY/hw6asXgJahg9c4rAmdDKL0PfPoXk8Nlj5v/YeBg47kh3ITPQ99TuE5nDJvY56bTvdybE2Ky0NR8qGBzshB+Ss5dZMywM/cOCtWbay9D7NMWTTIF5HcZjHKxckV0R6W80myTM8L3Ohr1oxCnUzf6m98Y/adM8hpq/wVHUyReUQg8vQBjNOBGJvZoKw5sOxfMMBgPR4ckVUuYaVg+NAK/YvMyZjdATx7rC/GE4PY3q/EU/6AJUIeX38Rvz92g5ugvgOWp7S0VtNFCfjwvtUR92z6Yb/OroxtXOCJTHAuYWf5rLhd2D+nxM7bjgIloA8hGFvUTj0uEDUZCmxAeghZI8qV4VXQPq9S3frXxOA1htNYdCYTnHZFUE/KrLxmkk9E0nrVRtN3ASui4ms5DuXWLs2BYX1kxHrmOiEQLMARugoN07jDd9wPHWSH4UbpZ2kWyN/m2v9gST4JZpA5miNcyvJNp3oLvmz8tIXnoll3+h1Svyq6MOkm4ATyyazCGrilOGsmvPFtbrL8YdqXnWf+RxpEL8z6qqSUP96SAuur/VfQ5dQ80/6313lEHqqGb+VFWomeSar647dcunENC4QnQv+P+DnuyR0CxXsAYRNdBn4Rdlu3m7NW+P5sPPudB326SiL8A==
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: fortune-secret
      name: fortune-secret
      namespace: workshp

